name: Build

on:
  workflow_dispatch:
    inputs:
      target:
        description: "spaces target to build (e.g. //devutils:install)"
        required: true
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-14
          - runner: ubuntu-22.04

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: work-spaces/spaces-checkout-run@015a2962707cc35c3936a52c4193bf546357dad7
        with:
          checkout: --url=https://github.com/work-spaces/devutils --rev=${{ github.ref_name }}
          run: ${{ inputs.target }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
