name: Publish for Platform

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to publish (defaults to the current ref name)
        required: false
        type: string
      target:
        description: Target to execute (default is build and publish)
        required: false
        type: string
        default: "//devutils:devutils"
      runner:
        description: Runner / OS
        required: true
        type: choice
        options:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
          - macos-13
          - windows-2022
      extra-checkout-args:
        description: Extra checkout args
        required: false
        type: string
        default: ""


permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: work-spaces/spaces-checkout-run@v0.21.3
        with:
          checkout: --url=https://github.com/work-spaces/devutils --rev=${{ inputs.tag || github.ref_name }} ${{ inputs.extra-checkout-args }}
          run: ${{ inputs.target }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
