name: Publish for Platform

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to publish (defaults to the current ref name)
        required: false
        type: string
      runner:
        description: Runner / OS
        required: true
        type: choice
        options:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
          - macos-13
          - windows-2022


permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: work-spaces/spaces-checkout-run@v0.20.7
        with:
          checkout: --url=https://github.com/work-spaces/devutils --rev=${{ inputs.tag || github.ref_name }}
          run: //devutils:devutils
          github-token: ${{ secrets.GITHUB_TOKEN }}
