name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-14
          - runner: ubuntu-22.04

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: work-spaces/spaces-checkout-run@455a73b87cb543d8d14988980b3ed825b293fef1
        with:
          checkout: --url=https://github.com/work-spaces/devutils --rev=${{ github.ref_name }}
          run: //devutils:devutils
          github-token: ${{ secrets.GITHUB_TOKEN }}
